### ISSUE TITLE
مجوز/لایسنس

### ISSUE THREAD

**Issue by alefvanoon** [rezatajari/learnmeabitcoin#11]
در مورد لایسنس این مخزن‌ نمی‌خواید تصمیمی بگیرید؟

**Comment by rezatajari** [comment]
لایسنس خاصی مد نظر داری ؟
فک کنم متن باز تنظیمش کنم بره رد کارش، نظرت چیه ؟

**Comment by alefvanoon** [comment]
من پیشنهادم GFDL هست.

**Comment by alefvanoon** [comment]
مثل اینکه لایسنس MIT در نظر گرفته شده  برای این مخزن.
 @Ziya-Sadr @ZeeAmini @alidevjimmy @rezak0
 ممنون می‌شم  کسانی که مشارکت کردند اگر مشکلی یا ایده‌ای دارند در مورد این اتفاق نظرشون رو اعلام کنن.

**Comment by rezak0** [comment]
به نظر من هم لایسنس
MIT 
براساس خود مخزن بیت کوین و فلسفه اون برای این مخزن مناسب هست.

**Comment by ZeeAmini** [comment]
سلام دوستان؛
واسه ترجمه به نظر من نیازی به لایسنس نیست ولی اگر تمایل دارید این می تونه گزینه مناسبی باشه:
https://en.wikipedia.org/wiki/Permissive_software_license

اما اگر کسی علاقه‌مند به طراحی اپ بیتکوینی بر اساس همین سایت لرن‌می‌ابیتکوین هست من خوشحال می‌شم راجع‌به ایده‌ش صحبت کنیم.

**Comment by Ziya-Sadr** [comment]
من بررسی نکردم تفاوتا رو.. موافق نظری هستم که جمع بهش برسه :)

**Comment by alidevjimmy** [comment]
سلام
به نظرم لایسنس خوبیه، موافقم.

**Comment by alefvanoon** [comment]
ممنون از همگی بابت این مخزن فوق‌العاده. همه نظرشون روی MIT بود.
#12
