### ISSUE TITLE
اضافه کردنTODO برای readme

### ISSUE THREAD

**Issue by HT696** [rezatajari/learnmeabitcoin#14]
بد نیست یه todo list اضافه بشه که کسی که ممکنه تمایل به مشارکت داشته باشه بدونه چطور میتونه کمک کنه
 مثلا شامل ترجمه صفحه اصلی معرفی، ترجمه و اضافه کردن بخش تکنیکال، اضافه کردن ابزارها و ترجمه عکس ها

**Comment by rezatajari** [comment]
دمت گرم
بهش فکر نکرده بودم که به این شکل نقشه راه تایید کنم، با اینحال بدم نیستش اینطوری منسجم تر میشه و گسترده ترش میشه کرد، یک راه ارتباطی می تونی بهم بدی با هم بیشتر در بارش حرف بزنیم اگه تمایل داری

**Comment by HT696** [comment]
تلگرام پیام دادم

**Comment by rezatajari** [comment]
با تصمیم گیری و بررسی انجام گرفته قرار بر شد یک ایشو مجزا برای ارائه تسک ها و گفتگوی پیرامونش تشکیل بشه که بزودی هم لیست اولیه ToDo هم ایشو قرار خواهد گرفت.
تشکر بابت توجهت حسام

**Comment by rezatajari** [comment]
@all-contributors please add @alefvanoon for bug report, ideas, Design

**Comment by rezatajari** [comment]
@all-contributors please add @HT696 for bug report, ideas, Design
