### ISSUE TITLE
ناخوانا بودن عکس ها

### ISSUE THREAD

**Issue by HT696** [rezatajari/learnmeabitcoin#15]
عکس ها فایل های png شفافند و رنگ‌بندیشون با پس زمینه روشن [سایت اصلی](https://learnmeabitcoin.com/) لحاظ شده در پس زمینه تیره‌ی [وبسایت](https://learnmeabitcoin.simorgh.me/) خوانایی بسیار ضعیفی دارن

**Comment by rezatajari** [comment]
آره درسته، بزار ببینم به الف و نون میتونم انتقال بدم که اگه بشه تناژ بک گراند رو عوض کنه، خیلی ممنون بابت نکاتی که می گی.

**Comment by alefvanoon** [comment]
سلام، چه رنگی باشه بهتره به نظرتون؟

**Comment by rezatajari** [comment]
الف دمت گرم، خوانایی بهتری گرفت 🍻

**Comment by rezatajari** [comment]
@all-contributors please add @HT696  for idea, bug report, Design

**Comment by rezatajari** [comment]
@all-contributors please add @HT696 for idea, bug report, Design
