### ISSUE TITLE
ایراد ترجمه در بخش سختی شبکه

### ISSUE THREAD

**Issue by this-is-not-a-user** [rezatajari/learnmeabitcoin#29]
نقل قول از بخش سختی شبکه:
"سختی شبکه مقدار زمانیه که یک ماینر (استخراج‌گر) بتونه بلاکی رو استخراج و بعد فرآیند استخراج‌کردن بلاک بعدی رو شروع کنه."
-اوایل صفحه

سختی شبکه زمان استخراج یک بلاک نیست بلکه زمان استخراج یک بلاک وابسته به سختی شبکه است.

**Comment by rezatajari** [comment]
بله حق با شماست 
تصحیح میکنم این قسمت رو
ممنون بابت تذکر

**Comment by rezatajari** [comment]
@all-contributors please add @this-is-not-a-user for Translation
